wandb:
    enabled: False
    project: "HF_SemSeg"
    run_name: ${checkpoint.model_name}

dataset:
    root: "/home/panos/Documents/data/kitti/data_semantics/training"
    H: 375
    W: 1242
    num_workers: 4
    num_classes: 35

augmentation:
    crop_height: 224
    crop_width: 224

train:
    batch_size: 8
    learning_rate: 1e-3
    num_epochs: 10000

model:
    backbone: "facebook/dinov2-base"  # small | base | large
    freeze_backbone: True

checkpoint:
    model_name: "dinob_up"
    comment: "base model, frozen backbone, augmentation"

visualization:
    attention: False
