wandb:
    enabled: False
    project: "HF_SemSeg"
    run_name: ${checkpoint.model_name}

dataset:
    root: "/home/panos/Documents/data/kitti-360"
    H: 375
    W: 1242
    num_workers: 4
    num_classes: 33

augmentation:
    crop_height: 320
    crop_width: 1024

train:
    epoch_size: 200 # number of batches per epoch
    accum_steps: 8 # number of batches per gradient accumulation step
    batch_size: 4  # number of images per batch
    learning_rate: 1e-3
    num_epochs: 100

model:
    backbone: "facebook/dinov2-base"  # small | base | large
    freeze_backbone: True
    patch_size: 14
    hidden_size: 128
    decoder_channels: 256
    deepsup_layers: [3, 6, 9]
    deepsup_weight: 0.4

checkpoint:
    model_name: "mask2former"
    comment: "base model, frozen backbone, augmentation"

visualization:
    attention: False
