wandb:
    project: "HF_SemSeg"
    run_name: ${checkpoint.model_name}

dataset:
    root: "/home/panos/Documents/data/kitti/data_semantics/training"
    H: 375
    W: 1242
    num_workers: 4
    num_classes: 35

train:
    batch_size: 1
    learning_rate: 1e-4
    num_epochs: 100

model:
    freeze_backbone: False

checkpoint:
    model_name: "finetune_dino"
    comment: "base model, un-frozen backbone, no augmentation"
