wandb:
    enabled: True
    project: "HF_SemSeg"
    run_name: ${checkpoint.model_name}

dataset:
    root: "/home/panos/Documents/data/kitti-360"
    H: 375
    W: 1242
    num_workers: 4
    num_classes: 33

augmentation:
    crop_height: 280 # divisible by 14
    crop_width: 840  # divisible by 14

train:
    batch_size: 8
    learning_rate: 1e-3
    num_epochs: 20

model:
    backbone: "facebook/dinov2-base"  # small | base | large
    freeze_backbone: True
    patch_size: 14
    decoder_channels: 256

checkpoint:
    model_name: "dino-unet-256-hd-crop"
    comment: "base model, frozen backbone, augmentation"

visualization:
    attention: False
